### ISSUE TITLE
[Bug]: In any channel's page the videos rows expand outside the screen

### ISSUE THREAD

**Issue by AhmeSaeed** [misspent/Darkened-Stylus-Themes#1]
### 🔍 Did you check former issues?

- [X] I have checked other issues

### 🖥️ What theme are you making this request for?

YouTube

### 📝 Describe the bug in detail

In any channel's page the videos rows expand outside the screen

### 📸 Screenshots

```bash
https://www.flickr.com/gp/198626053@N03/zkZr21NU40
```

### ➕ More the merrier

Is this a known issue ? or is it a problem at my end ?
If so how can I fix it ? I wanted to edit the script to lower the column count but I couldn't

**Comment by misspent** [comment]
I thought that'd happen on 1080p. Thank you for letting me know, and that was the update I pushed last night. I'll fix it asap.

**Comment by misspent** [comment]
I've released an update that has momentarily resolved the issue. I'll attempt to get it working with configurable options for 1080p later, but if you want to mess with it yourself, go to the:  
`/* |=> More Results - Channels section <=| */` section   
Edit the `@media (min-width 1500px)` and `--ytd-rich-grid-items-per-row` till you get something you like.  

If you do find something you like, please let me know and show me what it looks like for you so I can update the theme accordingly.

**Comment by AhmeSaeed** [comment]
I won't be able to test right now but I'll do when I can
