### ISSUE TITLE
[Bug]: Live chat panel blocked (this was BetterTV)

### ISSUE THREAD

**Issue by Ku4eR-89** [misspent/Darkened-Stylus-Themes#2]
### 🔍 Did you check former issues?

- [X] I have checked other issues

### 🖥️ What theme are you making this request for?

YouTube

### 📝 Describe the bug in detail

The script (YouTube: Styled version 20231221.16.53) hides the live chat panel on the stream because of this, any action with the page is blocked. Please check

**Comment by misspent** [comment]
Change the following in the code to "Inherit/Initial/flex":


```
--Show-Chat-Replay-Button: none;
--Show-Chat-Replay-Disabled-Premiere-Button: none;
```

If that doesn't work, even though it should, then feel free to let me know and give me more context on exactly what the issue is, as I've never had anything "blocked"

**Comment by Ku4eR-89** [comment]
Thank you. Sorry if I sounded rude, the problem wasn't entirely in your
code, BatterTTV caused a conflict with your code, I didn't realize it right
away. (the conflict is with the hidden chat). Add log.


вт, 26 дек. 2023 г. в 13:42, misspent ***@***.***>:

**Comment by misspent** [comment]
Tis all good, and you didn't come across as rude. Thank you for letting me know. I'll for sure keep that in mind.

Are you on about [this](https://betterttv.com) extension?

**Comment by Ku4eR-89** [comment]
Yes, that

вт, 26 дек. 2023 г. в 15:33, misspent ***@***.***>:
